### ISSUE TITLE
ui busted in v3.11: init is not a function

### ISSUE THREAD

**Issue by gbrownmozilla** [mozilla-releng/balrog#2384]
After updating to v3.11 I realized the admin ui is busted. Running locally I see this error:

Uncaught TypeError: init is not a function
    mountLazyComponent react-dom.development.js:17663
    beginWork react-dom.development.js:19056
    callCallback react-dom.development.js:3946
    invokeGuardedCallbackDev react-dom.development.js:3995
    invokeGuardedCallback react-dom.development.js:4057
    beginWork$1 react-dom.development.js:23965
    performUnitOfWork react-dom.development.js:22780
    workLoopSync react-dom.development.js:22708
    renderRootSync react-dom.development.js:22671
    performSyncWorkOnRoot react-dom.development.js:22294
    flushSyncCallbackQueueImpl react-dom.development.js:11328
    unstable_runWithPriority scheduler.development.js:646
    runWithPriority$1 react-dom.development.js:11277
    flushSyncCallbackQueueImpl react-dom.development.js:11323
    flushSyncCallbackQueue react-dom.development.js:11310
    flushPassiveEffectsImpl react-dom.development.js:23621
    unstable_runWithPriority scheduler.development.js:646
    runWithPriority$1 react-dom.development.js:11277
    flushPassiveEffects react-dom.development.js:23448
    commitBeforeMutationEffects react-dom.development.js:23325
    workLoop scheduler.development.js:590
    flushWork scheduler.development.js:545
    performWorkUntilDeadline scheduler.development.js:157
    EventHandlerNonNull* scheduler.development.js:180
    <anonymous> scheduler.development.js:843
    node_modules vendors~index.js:287
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    <anonymous> index.js:6
    node_modules vendors~index.js:299
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    <anonymous> react-dom.development.js:19
    <anonymous> react-dom.development.js:26321
    node_modules vendors~index.js:251
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    <anonymous> index.js:37
    node_modules vendors~index.js:263
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    <anonymous> index.jsx:4
    jsx index.js:130
    __webpack_require__ runtime.js:854
    fn runtime.js:151
    0 index.js:287
    __webpack_require__ runtime.js:854
    checkDeferredModules runtime.js:46
    webpackJsonpCallback runtime.js:33
    <anonymous> index.js:1

**Comment by gbrownmozilla** [comment]
Locally, I find the ui loads if I roll back the upgrade of @hot-loader/react-dom from bac0fa579c25b58f6b8cb250ab96c09b6de7e7ae.
